In [ ]:
# DO NOT modify this cell.
filename = "Buchtel.pgm"
verticalSeam2Remove = 10
horizontalSeam2Remove = 8

# Yes, you can create your own test cases and you should. Do it in a new cell.

In [65]:
import numpy as np

def load_pgm_as_numpy_array(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()

    # Check if the file is in PGM format
    if lines[0].strip() != 'P2':
        raise ValueError("File is not in PGM format (P2)")

    # Extract image dimensions and maximum pixel value
    width, height = map(int, lines[2].split())
    max_value = int(lines[3])

    # Extract pixel values from the remaining lines
    pixel_values = []
    for line in lines[4:]:
        pixel_values.extend(map(int, line.split()))

    # Convert pixel values to a numpy array
    image_np = np.array(pixel_values).reshape(height, width)

    return image_np, max_value

def calculate_energy(image):
    """Calculate energy of each pixel in the image with edge handling."""
    rows, cols = image.shape
    energy = np.zeros_like(image)

    for y in range(0, rows):
        for x in range(0, cols):
            energy[y][x] = abs(image[y,x] - image[y-1 if y-1>=0 else 0,x]) + \
                           abs(image[y,x] - image[y+1 if y+1<rows else rows-1,x]) + \
                           abs(image[y,x] - image[y,x-1 if x-1>=0 else 0]) + \
                           abs(image[y,x] - image[y,x+1 if x+1<cols else cols-1])
    return energy

def calculate_cumulative_energy(energy):
    rows, cols = energy.shape
    cumulative_energy = np.zeros_like(energy)

    # Copy the first row of energy into cumulative_energy
    cumulative_energy[0, :] = energy[0, :]

    # Fill in the rest of the cumulative energy matrix
    for y in range(1, rows): # Start from the second row
        for x in range(0, cols):
            cumulative_energy[y][x] = min(
                                      energy[y][x] + cumulative_energy[y-1][x-1] if x-1>=0 else float('inf'),
                                      energy[y][x] + cumulative_energy[y-1][x],
                                      energy[y][x] + cumulative_energy[y-1][x+1] if x+1<cols else float('inf'))

    return cumulative_energy

def seam_carve(image):
    """Perform seam carving on the image."""
    energy = calculate_energy(image)
    cumulative_energy = calculate_cumulative_energy(energy)
    print(energy)
    print(cumulative_energy)

# Define the image numpy array
img = np.array([
    [2, 10, 70],
    [155, 30, 10],
    [200, 190, 120],
    [10, 255, 60]
]);

seam_carve(img, 0)


[[161  88 120]
 [323 325 190]
 [245 305 240]
 [435 505 255]]
[[ 161   88  120]
 [ 411  413  278]
 [ 656  583  518]
 [1018 1023  773]]


In [ ]:
import os

def save_pgm(image_filepath, image_np, max_value, v, h):
    """Save a numpy array as a PGM file."""
    base_filename, ext = os.path.splitext(os.path.basename(image_filepath))
    output_directory = 'test/myProcessed/'
    output_filename = f"{output_directory}{base_filename}_processed_{v}_{h}.pgm"

    with open(output_filename, 'w') as file:
        # Write PGM header
        file.write("P2\n")
        file.write(f"# Created by seam carving \n")
        file.write(f"{image_np.shape[1]} {image_np.shape[0]}\n")  # Width and height
        file.write(f"{max_value}\n")  # Maximum pixel value

        # Write pixel values
        for row in image_np:
            file.write(" ".join(map(str, row)) + "\n")

    print(f"Processed image saved as: {output_filename}")

def process_image(image_filepath, num_seams):
    """Process the image by seam carving and save the result."""
    image_np, max_value = load_pgm_as_numpy_array(image_filepath)
    processed_image = seam_carve(image_np, num_seams)  # Perform seam carving

    save_pgm(image_filepath, processed_image, max_value, num_seams, 0)  # Save the processed image

# User inputs
# image_filename = input("Enter the image file name: ")
# num_seams = int(input("Enter the number of vertical seams to remove: "))

# For testing
image_filepath = './test/raw/CAS.pgm'
vertical_seams = 20

# Entry Point for Part I
process_image(image_filepath, vertical_seams)


In [ ]:
# Test cell

my = "./test/myProcessed/CAS_processed_20_0.pgm"
correct = "./test/processed/CAS_processed_20_0.pgm"

import filecmp
filecmp.cmp(my, correct)

In [ ]:
# Part II : both vertical and horizontal seams removal
# Save your processed file to img_processed_v_h.pgm
filename2 = filename.split(".")[0]+"_processed_"+ \
            str(verticalSeam2Remove)+"_"+str(horizontalSeam2Remove)+".pgm"
print(filename2)

# your code, add cells as you need

In [ ]:
# This is for graduate students only
filenameG = "flower.ppm"
vSeam2Remove = 20
hSeam2Remove = 25

In [ ]:
# This is for graduate students only
# Part III : color img in ppm
filenameG2 = filenameG.split(".")[0]+"_processed_"+ \
            str(vSeam2Remove)+"_"+str(hSeam2Remove)+".ppm"
print(filenameG2)
# your code, add cells as you need